# Generated by Django 5.1.4 on 2025-03-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.base')),
                ('tag', models.CharField(max_length=50)),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.blog')),
            ],
        ),
    ]
