# Generated by Django 5.1.4 on 2025-03-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.base')),
                ('event_type', models.CharField(choices=[('face to face', 'FACE TO FACE'), ('online', 'Online')])),
                ('link', models.CharField()),
                ('starting_day', models.DateTimeField()),
                ('ending_day', models.DateTimeField()),
                ('number_of_sites', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField()),
            ],
            bases=('base.base',),
        ),
    ]
