# Generated by Django 5.1.4 on 2025-03-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.base')),
                ('image', models.ImageField(upload_to='audio_book/images')),
            ],
            bases=('base.base',),
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_book/files')),
                ('audio_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='audio_book.audiobook')),
            ],
        ),
    ]
